export const GLOSSARY: Record<string, string> = {
  inpc: "El Índice Nacional de Precios al Consumidor. Mide en promedio cuánto suben los precios de lo que compramos día a día.",
  inflación: "El aumento generalizado de los precios. Cuando sube, tu dinero vale menos.",
  "inflación subyacente": "La medida más pura de la inflación, ya que descarta los precios muy volátiles como la gasolina o ciertos alimentos.",
  inpp: "Índice Nacional de Precios al Productor. Es la inflación vista desde las fábricas y empresas (cuánto les cuesta producir).",
  pib: "Producto Interno Bruto. Es casi todo el dinero y riqueza (bienes y servicios) que genera México en total.",
  tasa: "Tasa de interés de Banco de México (Banxico). Es el costo de pedir dinero prestado. Si sube, los créditos son más caros.",
  tiie: "Tasa de Interés Interbancaria de Equilibrio. Una tasa de referencia que usan los bancos para prestarse dinero.",
  uma: "Unidad de Medida y Actualización (UMA). Se usa en México para cobrar multas y créditos (sin afectar al salario mínimo).",
  pea: "Población Económicamente Activa. Es el conteo de todas las personas en México que trabajan o activamente buscan empleo.",
  cetes: "Certificados de la Tesorería. Una forma súper segura de inversión: le prestas tu dinero al Gobierno de México y él te paga intereses garantizados.",
  nearshoring: "Un fenómeno donde empresas enormes mudan sus fábricas de Asia hacia México para estar pegados a su gran cliente: Estados Unidos.",
  remesas: "Dinero que nuestros paisanos ganan trabajando en Estados Unidos (u otros países) y envían a sus familias en México.",
  afores: "Las Administradoras de Fondos para el Retiro. Las empresas privadas que guardan y hacen crecer el ahorro de tu pensión laboral.",
  rezago: "Atraso notable. Por ejemplo, en educación significa gente que no completó estudios básicos; en vivienda, casas sin servicios.",
  hacinamiento: "Vivir en un espacio sobrepoblado dentro de una casa (demasiada gente amontonada por habitación).",
  riesgo: "En macroeconomía, el Riesgo País (EMBI). Indica a los inversionistas extranjeros qué tan probable es que México no pague sus deudas.",
  créditos: "Préstamos otorgados por instituciones bancarias (tarjetas, nómina, hipotecas).",
  sindicalización: "El acto de afiliarse o pertenecer a un Sindicato oficial que defienda los derechos laborales colectivos.",
  mortalidad: "En estadística, es el número proporcional de cruces o defunciones en una población y tiempo determinados.",
  "esquema de vacunación": "La cartilla o programa de vacunas básicas obligatorias y gratuitas para prevención en México.",
};
